export const FETCH_CATEGORIES="FETCH_CATEGORIES" //lấy danh mục
export const FETCH_COURSE_CATEGORIES="FETCH_COURSE_CATEGORIES" //lấy khóa học danh mục
export const FETCH_COURSES="FETCH_COURSES"
export const FETCH_COURSES_DETAIL="FETCH_COURSES_DETAIL"//lấy chi tiết khóa học
export const ADD_COURSES="ADD_COURSES"
//giỏ hàng
export const ADD_TO_CART="ADD_TO_CART"
export const DELETE_TO_CART="DELETE_TO_CART"
//user
export const FETCH_CREDENTIALS="FETCH_CREDENTIALS"
export const SET_CREDENTIALS_EMPTY="SET_CREDENTIALS_EMPTY"
//search
export const SEARCH_COURSES="SEARCH_COURSES"
export const SEARCH_USER="SEARCH_USER"
//admin
export const FETCH_USERS="FETCH_USERS"
export const ADD_USERS="ADD_USERS"
export const DELETE_USERS="DELETE_USERS"
export const FETCH_COURSE_ADMIN="FETCH_COURSE_ADMIN"
